- name: Copy zshrc to all hosts
  hosts: all
  tasks:
    - name: Copy file
      copy:
        src: /home/danielguichard/ansible-files/.zshrc
        dest: /home/danielguichard/.zshrc
        owner: danielguichard
        group: danielguichard
