- name: Copy zshrc to all hosts
  become: true
  become_user: danielguichard
  hosts: all
  tasks:
    - name: Copy .zshrc
      copy:
        src: /home/danielguichard/.zshrc
        dest: /home/danielguichard/.zshrc
    - name: Copy .p10k.zsh
      copy:
        src: /home/danielguichard/.p10k.zsh
        dest: /home/danielguichard/.p10k.zsh
