- hosts: docker_hosts
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - python3-pip

    - name: add user permissions
      shell: usermod -aG docker danielguichard

    - name: deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        command: --schedule "0 0 4 * * *"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
        
    - name: Pull the latest images for all services in docker-compose
      ansible.builtin.shell: docker compose pull
      args:
        chdir: "{{ compose_project_path }}"
    - name: Start containers with the latest images
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: "{{ compose_project_path }}"

    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
