- hosts: docker_hosts
  become: true
  tasks:
    - name: Install packages
      apt: 
        name:
          - python3-pip
    
    - name: add user permissions
      shell: usermod -aG docker danielguichard

    - name: Install python sdk
      pip:
        name:
          - docker
          - docker-compose

    - name: deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: containrrr/watchtower
        command: --schedule "0 0 4 * * *"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
        
    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
